### ISSUE TITLE
vue側でのAPI動作確認

### ISSUE THREAD

**Issue by katchannn** [katchannn/securityNewsAggregator#14]

**Comment by kamaaaa0124** [comment]
vue側のJavascriptでapiを呼び出す際、apiのURLはどのように指定すればいいでしょうか・・・？
例えば
request.open('GET', 'http～で始まるURL', true);

の部分です。

**Comment by katchannn** [comment]
backend側のコンテナも立ち上げたうえで`http://localhost:8080/`でやってみてもらえますか？
