### ISSUE TITLE
ニュースデータのDB格納

### ISSUE THREAD

**Issue by katchannn** [katchannn/securityNewsAggregator#24]

**Comment by KKTT4isei** [comment]
とりあえずDB格納までが出来そうなの完成したけど，mainから呼び出すget_news()が起動してなさそうで確認できない... 
awaitつけるとエラー返されるし，外すと何も動いてなさそう．俺が非同期処理周りよく分かってないコード書いてるからな気はする．

**Comment by katchannn** [comment]
whileとか全部なくしてget_news()だけ呼ぶようにしてもだめかな？

**Comment by KKTT4isei** [comment]
なんとか挙動そのままに形少し変えて動くようにはなったよ
ただDBとGPTと殴り合いして発狂してる

**Comment by KKTT4isei** [comment]
とりあえずDB登録までは出来るようになったよ!
注意なんだけど,titleデータベースが先に全部処理されて,登録された数に応じてnewsデータベース登録するコードなので,どっかで詰まってやり直すときにnewsはスカスカなのにタイトル埋まってるせいでなにもしょりされなくなる...
これを/docsに表示させるにはroutersのnews.pyいじる感じだよね

**Comment by katchannn** [comment]
ないすー
あとで全体の流れと挙動みとく
docsに表示させるのは@kova-1242 の担当部分だけど，routersとcrudsをいじる感じだね

**Comment by KKTT4isei** [comment]
了解～
そっちは @kova-1242 に任せようかな
取り敢えずリファクタリングしてマシなコードにしときます
