### ISSUE TITLE
HTMLからテキストに変換する

### ISSUE THREAD

**Issue by katchannn** [katchannn/securityNewsAggregator#3]

**Comment by katchannn** [comment]
html2textを使うだけだと無駄な情報がまだ多い→chatGPTに投げるトークン数が増えてしまうため良くない
専用のformatterがいるかも

**Comment by KKTT4isei** [comment]
customprofile(大嘘)に解決したっぽいコード投げといた

**Comment by katchannn** [comment]
よさそうなんでマージする
